### ISSUE TITLE
i18n loading local translation files

### ISSUE THREAD

**Issue by MounirHamani** [Ipstenu/join-my-multisite#6]
Hey Mika,

Would you accept a small pull request adding support for loading translations from a languages folder (inside the plugin) ?

As a side note, according to WP coding standards, you should add spaces around function parameters like so `function_call( $param )`

Have a nice day.

**Comment by Ipstenu** [comment]
Coding standards are recommended, not required. I'll eventually fix those things as I update.

However I would not accept a pull request for including languages inside the plugin as those (should be) unnecessary. You can put your languages in the wp-content/languages/ folders. They shouldn't be in the plugin itself. You can submit translations 

https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/
https://translate.wordpress.org/projects/wp-plugins/join-my-multisite

**Comment by MounirHamani** [comment]
@Ipstenu You are right, I forgot about the reversal of order in WP 4.6.

Regarding the coding standards, you are right as well but it's still better when they are followed. :) I can easily reformat the code for you if you want.

I will add my translation when I have got some time to finish it. I only translated the frontend, and part of it I copied it from the regular WP register form.

**Comment by Ipstenu** [comment]
I'm not disagreeing about the standards, only pointing out that they're low priority. I'll get to it, but a pull request that _just_ cleans it up is likely to conflict with any non-committed dev work I have going on at the moment :)
